module.exports = {
  name: "fancy",
  aliases: ["fancytext"],
  description: "Gives you cool 𝔣ancy text",
  async run(bot, message, args) {
    const a = args
      .join(" ")
      .replace("A", "𝔄")
      .replace("B", "𝔅")
      .replace("C", "ℭ")
      .replace("D", "𝔇")
      .replace("E", "𝔈")
      .replace("F", "𝔉")
      .replace("G", "𝔊")
      .replace("h", "ℌ")
      .replace("I", "ℑ")
      .replace("J", "𝔍")
      .replace("K", "𝔎")
      .replace("L", "𝔏")
      .replace("M", "𝔐")
      .replace("N", "𝔑")
      .replace("O", "𝔒")
      .replace("P", "𝔓")
      .replace("Q", "𝔔")
      .replace("R", "ℜ")
      .replace("S", "𝔖")
      .replace("T", "𝔗")
      .replace("U", "𝔘")
      .replace("V", "𝔙")
      .replace("W", "𝔚")
      .replace("X", "𝔛")
      .replace("Y", "𝔜")
      .replace("Z", "ℨ")
      .replace("a", "𝔞")
      .replace("b", "𝔟")
      .replace("c", "𝔠")
      .replace("d", "𝔡")
      .replace("e", "𝔢")
      .replace("f", "𝔣")
      .replace("g", "𝔤")
      .replace("h", "𝔥")
      .replace("i", "𝔦")
      .replace("j", "𝔧")
      .replace("k", "𝔨")
      .replace("l", "𝔩")
      .replace("m", "𝔪")
      .replace("n", "𝔫")
      .replace("o", "𝔬")
      .replace("p", "𝔭")
      .replace("q", "𝔮")
      .replace("r", "𝔯")
      .replace("s", "𝔰")
      .replace("t", "𝔱")
      .replace("u", "𝔲")
      .replace("v", "𝔳")
      .replace("w", "𝔴")
      .replace("x", "𝔵")
      .replace("y", "𝔶")
      .replace("z", "𝔷");
    message.channel.send(a);
  },
};
